### PR TITLE
Update apply REST handler

### PR DESCRIPTION
**Pull request by alexellis**
The HTTP handler appeared to generate errors with the latest
versions of Kubernetes (1.17.5 and 1.18). A function created
via REST and then updated via a CRD or visa-versa caused an
error about the RevisionVersion being required.

By getting the function object before updating it, this
appears to resolve the issue.

Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>

### CODE REVIEW

**Comment by alexellis** [comment]
Wasn't keen to write fixes 630 since there's more to it.

**Comment by LucasRoesler** [comment]
@alexellis can you provide some more details on what else needs to be covered/handled?  When i read the original issue, the only true error I saw was the one about ResourceVersion and this will clearly handle that case.

**Comment by alexellis** [comment]
Hi @LucasRoesler the comment is about https://github.com/openfaas/faas-netes/issues/634 - I wanted to have it covered and tracked in a separate issue so that it doesn't get forgotten about. I'm happy to merge this fix when CI passes.

CI seems very flakey at the moment with KinD when it creates its second cluster for e2e tests.

Alex

**Comment by alexellis** [comment]
A separate PR was opened by @LucasRoesler to do the same thing this morning in: #633

**Pull request merged**
