### PR TITLE
Fixes #350 by adding missing namespace to ingress resource template

### LINKED ISSUE #350: Namespace is not set for ingress
After deploying OpenFaaS with the helm generated, ingress enabled yaml: 
`helm template faas-netes/chart/openfaas     --name openfaas     --namespace openfaas      --set basic_auth=true     --set functionNamespace=openfaas-fn  --set ingress.enabled=true > openfaas.yaml`

The ingress was created in the default namespace and not in the openfaas namespace and faas-cli was not able to connect.

## Expected Behaviour
The gateway should be accessible through the ingress.

## Current Behaviour
Gateway is not accessible.

## Possible Solution
Add `namespace: {{ .Release.Namespace | quote }}` to the ingress template https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/templates/ingress.yaml#L5

If the yaml is already generated one can add the `namespace: openfaas` line directly to the ingress specification.
If it's already deployed the ingress can be deleted and the ingress specification can be applied separately.

## Steps to Reproduce (for bugs)
Run the command above to generate the yaml and deploy it to a kubernetes cluster, then try to connect to OpenFaas.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
``` 
 CLI:
 commit:  5b36c50280d961d3aa248bd17f901f4ef2774447
 version: 0.8.1

Gateway
 uri:     https://openfaas.kube......
 version: 0.9.14
 sha:     a65df4795bc66147c41161c48bfd4c72f60c7434
 commit:  Update swagger for missing secret definitions


Provider
 name:          faas-netes
 orchestration: kubernetes
 version:       0.7.0
 sha:           ab9b56c0760eadba05762fa53dbe99d890bc9e19
```
* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5+coreos.0", GitCommit:"b8e596026feda7b97f4337b115d1a9a250afa8ac", GitTreeState:"clean", BuildDate:"2017-12-12T11:01:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux/ Ubuntu 16.04
* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

### PR DESCRIPTION
**Pull request by hullarb**
Signed-off-by: Bela Hullar <hullarb@gmail.com>

Adding missing namespace to the ingress resource template.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
https://github.com/openfaas/faas-netes/issues/350

## How Has This Been Tested?

Running `helm template faas-netes/chart/openfaas \
    --name openfaas \
    --namespace openfaas  \
    --set basic_auth=true \
    --set functionNamespace=openfaas-fn`  adds now the namespace that was missing earlier and after deployment (`kubctl apply`) the OpenFaaS gateway can be accessed.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Thank you for this very quick contribution. Can you show the curl / approach for accessing the gateway?

**Comment by hullarb** [comment]
sure, i just set the `OPENFAAS_URL` env var to the host configured in the ingress description and then used faas-cli to log in and to deploy and then with the same `hostname/function_path` invoking the deployed function from browser/curl.

**Comment by alexellis** [comment]
I spoke to Lucas who also approved the change.

I do wonder whether this change has any interactions with values.yml?

**Comment by hullarb** [comment]
Thanks for checking and the approval!

`values.yaml` should be not affected as i just reused a variable used in the other templates too and the documentation shows the example to provide it in the helm template command `--namespace openfaa`

**Comment by alexellis** [comment]
Merged, thank you for your PR.

**Comment by alexellis** [comment]
--
Join Slack to connect with the community
https://docs.openfaas.com

**Pull request merged**
