### PR TITLE
Refactor helm chart into more template files

### PR DESCRIPTION
**Pull request by LucasRoesler**
## Description
- Re-write template files so that they focus on one component and one
k8s kind.

## Motivation and Context

- Makes it easier to see and find the different components of the helm
chart
- I was asked by @alexellis to break up the template files so that different components would be easier to find. 

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

1. Deploy to minikube using 
```sh
helm install --debug -f openfaas/values.yaml --set "rbac=false" openfaas
```
- Navigate to the ui at `http://$(minikube ip):31112/ui`
- Create a new node info function using 
    - function: `functions/nodeinfo:latest`
    - fprocess: `node main.js`
    - network: `func_functions`
- invoke the function from the UI

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @LucasRoesler does this match the file organisation for the `yaml` branch? #105

**Comment by weikinhuang** [comment]
LGTM

**Comment by LucasRoesler** [comment]
@alexellis sorry I have been away for a bit, I will checkout that branch. and update accordingly

**Comment by alexellis** [comment]
Thank you @LucasRoesler if we could have that level of coupling to match my branch in `yaml` that'd be great. cc @rimusz

**Comment by LucasRoesler** [comment]
I just updated this to match the yaml file structure from master.  It should be one file (or two with a configmap)  per service that is deployed.

**Comment by alexellis** [comment]
Thank you for doing this. @rimusz suggested merging the more recent #119 so we didn't have to rebase yours. Would appreciate your input for the next few stages of getting the chart ready.

**Pull request closed without merging**
