### PR TITLE
[Need Help with Testing] Update images for prometheus and alertmanager

### PR DESCRIPTION
**Pull request by viveksyngh**
This commit updates yaml files to use multi architecture image for prometheus
and alertmanager. Prometheus is updated to v2.11.0 and alertmanager is updated
to v0.18.0.

Fixes: #422

Signed-off-by: Vivek Singh <vivekkmr45@yahoo.in>

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
#422 

## How Has This Been Tested?

Tested on local using Kind. 

```
./hey -z=30s -q 5 -c 2 -m POST -d=Test http://127.0.0.1:31112/function/echo

Summary:
  Total:	30.0138 secs
  Slowest:	0.0282 secs
  Fastest:	0.0049 secs
  Average:	0.0087 secs
  Requests/sec:	9.9954

  Total data:	1200 bytes
  Size/request:	4 bytes

Response time histogram:
  0.005 [1]	|
  0.007 [85]	|■■■■■■■■■■■■■■■■■■■■■■■■
  0.010 [141]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.012 [51]	|■■■■■■■■■■■■■■
  0.014 [15]	|■■■■
  0.017 [3]	|■
  0.019 [0]	|
  0.021 [0]	|
  0.024 [1]	|
  0.026 [1]	|
  0.028 [2]	|■


Latency distribution:
  10% in 0.0063 secs
  25% in 0.0071 secs
  50% in 0.0083 secs
  75% in 0.0095 secs
  90% in 0.0114 secs
  95% in 0.0128 secs
  99% in 0.0252 secs

Details (average, fastest, slowest):
  DNS+dialup:	0.0000 secs, 0.0049 secs, 0.0282 secs
  DNS-lookup:	0.0000 secs, 0.0000 secs, 0.0000 secs
  req write:	0.0000 secs, 0.0000 secs, 0.0010 secs
  resp wait:	0.0085 secs, 0.0048 secs, 0.0250 secs
  resp read:	0.0001 secs, 0.0000 secs, 0.0004 secs

Status code distribution:
  [200]	300 responses
```

```
kubectl get pods -n openfaas-fn --watch
NAME                    READY   STATUS    RESTARTS   AGE
echo-5cf679b455-kv6s9   1/1     Running   0          87m
echo-5cf679b455-bdmt6   0/1     Pending   0          0s
echo-5cf679b455-9zsfl   0/1     Pending   0          0s
echo-5cf679b455-k9v6w   0/1     Pending   0          0s
echo-5cf679b455-bdmt6   0/1     Pending   0          0s
echo-5cf679b455-9zsfl   0/1     Pending   0          0s
echo-5cf679b455-k9v6w   0/1     Pending   0          0s
echo-5cf679b455-vjv5r   0/1     Pending   0          0s
echo-5cf679b455-vjv5r   0/1     Pending   0          0s
echo-5cf679b455-bdmt6   0/1     ContainerCreating   0          0s
echo-5cf679b455-9zsfl   0/1     ContainerCreating   0          0s
echo-5cf679b455-k9v6w   0/1     ContainerCreating   0          0s
echo-5cf679b455-vjv5r   0/1     ContainerCreating   0          0s
echo-5cf679b455-9zsfl   0/1     Running             0          5s
echo-5cf679b455-vjv5r   0/1     Running             0          6s
echo-5cf679b455-9zsfl   1/1     Running             0          7s
echo-5cf679b455-k9v6w   0/1     Running             0          7s
echo-5cf679b455-bdmt6   0/1     Running             0          9s
echo-5cf679b455-k9v6w   1/1     Running             0          9s
echo-5cf679b455-vjv5r   1/1     Running             0          9s
echo-5cf679b455-bdmt6   1/1     Running             0          12s
echo-5cf679b455-9zsfl   1/1     Terminating         0          20s
echo-5cf679b455-bdmt6   1/1     Terminating         0          20s
echo-5cf679b455-vjv5r   1/1     Terminating         0          20s
echo-5cf679b455-k9v6w   1/1     Terminating         0          20s
echo-5cf679b455-bdmt6   0/1     Terminating         0          24s
echo-5cf679b455-9zsfl   0/1     Terminating         0          25s
echo-5cf679b455-k9v6w   0/1     Terminating         0          25s
echo-5cf679b455-vjv5r   0/1     Terminating         0          25s
echo-5cf679b455-9zsfl   0/1     Terminating         0          32s
echo-5cf679b455-9zsfl   0/1     Terminating         0          32s
echo-5cf679b455-k9v6w   0/1     Terminating         0          32s
echo-5cf679b455-bdmt6   0/1     Terminating         0          32s
echo-5cf679b455-bdmt6   0/1     Terminating         0          32s
echo-5cf679b455-vjv5r   0/1     Terminating         0          33s
echo-5cf679b455-bdmt6   0/1     Terminating         0          33s
echo-5cf679b455-bdmt6   0/1     Terminating         0          33s
echo-5cf679b455-k9v6w   0/1     Terminating         0          34s
echo-5cf679b455-k9v6w   0/1     Terminating         0          34s
echo-5cf679b455-vjv5r   0/1     Terminating         0          42s
echo-5cf679b455-vjv5r   0/1     Terminating         0          42s
echo-5cf679b455-9zsfl   0/1     Terminating         0          42s
echo-5cf679b455-9zsfl   0/1     Terminating         0          42s
```

Screen Shot 2019-09-08 at 2 33 11 AM

Screen Shot 2019-09-08 at 2 33 21 AM

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @viveksyngh 

This also changes the Prometheus version for the whole of OpenFaaS on Kubernetes.

Could you link to the change logs for the versions between where we are today and the new version?

Thanks,

Alex

**Comment by LucasRoesler** [comment]
Just read the Prometheus changelog, nothing immediately jumped out at me https://github.com/prometheus/prometheus/blob/master/CHANGELOG.md

**Comment by alexellis** [comment]
AlertManager -> https://github.com/prometheus/alertmanager/blob/master/CHANGELOG.md

**Comment by alexellis** [comment]
@viveksyngh please can you do a quick rebase?

Also remove the values from `yaml_armhf/` and ` yaml_arm64/`, I'm not sure if you're aware, but we generate these values now, so you just need to update the correct values_*.yaml file and the values will be be copied over next time I run `make charts`.

**Comment by viveksyngh** [comment]
I was not aware of that. I will do the rebase.

**Comment by viveksyngh** [comment]
I have rebased it .. I just wanted to know, if `make charts` updates the values in yaml files. Do we need to update files in `yaml` folder as well ?

**Comment by alexellis** [comment]
Hi, `yaml` is also updated.

Thanks again for this @viveksyngh 🥇 

Alex

**Pull request merged**
