### PR TITLE
Add environment variables to function response

### PR DESCRIPTION
**Pull request by daiwenlong**
Reader now return environment variables

Signed-off-by: daiwenlong <dwl0208@163.com>

## Description

Add environment variables to function response for  ```/systems/function/{functionName}```

examples:

```
{
  "name": "test-moudle-165235171490006966-9",
  "image": "test/test-moudle-165235171490006966:8",
  "namespace": "openfaas-fn",
  "envVars": {
    "TZ": "Asia/Shanghai",
    "test": "225667"
  },
  "labels": {
    "code_md5": "a18b1c8",
    "faas_function": "test-moudle-165235171490006966-9",
    "uid": "803204903"
  },
  "annotations": {
    "com.openfaas.health.http.path": "/_health",
    "prometheus.io.scrape": "false"
  },
  "limits": {
    "memory": "128Mi",
    "cpu": "50m"
  },
  "requests": {
    "memory": "128Mi",
    "cpu": "50m"
  },
  "replicas": 1,
  "availableReplicas": 1,
  "createdAt": "2022-05-27T09:11:48Z"
}
```
## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

```
/home/app # curl localhost:8080/system/function/test-moudle-165235171490006966-9 | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   526  100   526    0     0   326k      0 --:--:-- --:--:-- --:--:--  513k
{
  "name": "test-moudle-165235171490006966-9",
  "image": "test/test-moudle-165235171490006966:8",
  "namespace": "openfaas-fn",
  "envVars": {
    "TZ": "Asia/Shanghai",
    "test": "225667"
  },
  "labels": {
    "code_md5": "a18b1c8",
    "faas_function": "test-moudle-165235171490006966-9",
    "uid": "803204903"
  },
  "annotations": {
    "com.openfaas.health.http.path": "/_health",
    "prometheus.io.scrape": "false"
  },
  "limits": {
    "memory": "128Mi",
    "cpu": "50m"
  },
  "requests": {
    "memory": "128Mi",
    "cpu": "50m"
  },
  "replicas": 1,
  "availableReplicas": 1,
  "createdAt": "2022-05-27T09:11:48Z"
}
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi, thanks for your interest in openfaas.

Is there an issue you can link to, or do you need to create one for this?

Under "How Has This Been Tested?" we need to see your command for deploying a function, so that we can also run them and verify the changes.

Alex

**Comment by alexellis** [comment]
I thought that these variables were already returned from the /system/functions endpoint?

They are not intended to be returned from /system/function/NAME endpoint because it's used for polling during scale from zero.

Maybe @LucasRoesler can verify?

**Comment by LucasRoesler** [comment]
I am not opposed to standardizing the API a little bit so that responses are more intuitive, but @alexellis is right. 

If we wanted, we could move the polling endpoint to a special endpoint so that it is clearer that it should stay very minimal, something like `system/function/{name}/status`

But that is a slightly different topic

**Comment by daiwenlong** [comment]
`arkade install openfaas --basic-auth=false --set faasnetes.image=daiwenlong/faas-netes:dev2`

Deploy function using faas-cli deploy -f

```
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  test:
    lang: python
    image: daiwenlong/lang-test:latest
    environment:
      test: 1212
      url: http://xxx.com
```

Deploy and test 

```
root@gateway-wv52l:/home/app# faas-cli deploy -f test.yml
Deploying: test.

Deployed. 202 Accepted.
URL: http://127.0.0.1:8080/function/test

root@gateway-wv52l:/home/app# curl localhost:8080/system/function/test | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   310  100   310    0     0  62000      0 --:--:-- --:--:-- --:--:-- 62000
{
  "name": "test",
  "image": "daiwenlong/lang-test:latest",
  "namespace": "openfaas-fn",
  "envProcess": "python index.py",
  "envVars": {
    "test": "1212",
    "url": "http://xxx.com"
  },
  "labels": {
    "faas_function": "test"
  },
  "annotations": {
    "prometheus.io.scrape": "false"
  },
  "replicas": 1,
  "availableReplicas": 1,
  "createdAt": "2022-06-03T06:24:53Z"
}

```

**Comment by daiwenlong** [comment]
> I couldn't see why you wanted third changed.
> 
> Can you fill that out under "Motivation and Context"? Thanks

`fprocess` has been returned on  field `envProcess `, `fprocess` is not an environment variable set by developer.

**Comment by alexellis** [comment]
Just an update - we've done this for OpenFaaS Pro, but feel free to keep using your fork of the community edition (CE).

If it causes too much latency or load during polling by event connectors or scale from zero, we may put it behind a querystring flag i.e. ?detailed=1

**Pull request closed without merging**
