### PR TITLE
Profiles CRD toggle

### PR DESCRIPTION
**Pull request by alexellis**
Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>

## Description

Profiles CRD toggle

## Motivation and Context

Introduces a toggle for creating the Profiles CRD. This is
to help users overcome #686

The main use-case is for users who are installing within a 
restrictive environment, where they cannot create CRDs, but 
rely on an administrator to take on this role.

Makes a breaking change where "createCRDs" controls whether
any CRDs are created. This is on by default. Existing users
must take note when upgrading.

## How Has This Been Tested?

Perhaps some users would like to test?

createCRDs: false gave no CRDs in the cluster

createCRDs: true gave: profiles.openfaas.com

createCRDs: true with operator.create: true gave functions.openfaas.com and profiles.openfaas.com

createCRDs has been made "true" in the values.yaml file

### CODE REVIEW

**Comment by alexellis** [comment]
This solution is similar to what was asked for here -> https://github.com/openfaas/faas-netes/pull/579#issuecomment-719593185 by @SpaWn2KiLl

**Comment by alexellis** [comment]
@Gottox @SpaWn2KiLl @ArcticXWolf @RichterBIT

**Comment by ArcticXWolf** [comment]
Shouldn't these RBAC definitions be disabled too, if profiles are not enabled?

https://github.com/openfaas/faas-netes/blob/08ffc578d054f407458a6279c31216d6155ef7da/chart/openfaas/templates/controller-rbac.yaml#L76
https://github.com/openfaas/faas-netes/blob/08ffc578d054f407458a6279c31216d6155ef7da/chart/openfaas/templates/controller-rbac.yaml#L185
https://github.com/openfaas/faas-netes/blob/08ffc578d054f407458a6279c31216d6155ef7da/chart/openfaas/templates/controller-rbac.yaml#L206

**Comment by alexellis** [comment]
Potentially, however it is not causing an error at deployment time. Feel free to try it out.

**Comment by ArcticXWolf** [comment]
I did, but in my cluster I do not have the rights to grant the `{{ .Release.Name }}-profiles` role (yes, I am currently in discussion with getting more access). However since this role is not needed, we dont need to deploy it? 

When I use the `{{- if .Values.createCRDs }}` in line 76 and 186 of controller-rbac.yaml I can deploy the chart fine.

**Comment by alexellis** [comment]
That makes me think of something else. If we put those parts behind the same if statement, then what is the story for your administrator? How will he/she install those parts on your behalf?

**Comment by ArcticXWolf** [comment]
Sorry, I am not quite sure what these CRDs are used for in OpenFaaS. Are they mandatory for the installation? I would've just skipped it for now (the chart seems to install just fine without) and instructed my administrator to either provide me with enough permissions at a later time or install the CRDs manually.

**Review by LucasRoesler — CHANGES_REQUESTED** [review]
This adds a new value, which should be documented in the chart readme too https://github.com/openfaas/faas-netes/tree/master/chart/openfaas#configuration

**Comment by alexellis** [comment]
I'll get that done @LucasRoesler - anything else, or otherwise happy for this to be merged?

**Comment by LucasRoesler** [comment]
> I'll get that done @LucasRoesler - anything else, or otherwise happy for this to be merged?

That is it

**Comment by alexellis** [comment]
OK, I've just done that.

**Review by LucasRoesler — APPROVED** [review]

**Comment by ArcticXWolf** [comment]
So we keep the roles in the chart? Or shall this be addressed in a different issue?

**Comment by alexellis** [comment]
Please can you raise a separate issue for discussion?

**Comment by ArcticXWolf** [comment]
Sure thing, I've created #697 . Thanks for all your work 👍

**Comment by alexellis** [comment]
I think it's been mentioned before but we can do even more to help customers through our [Premium Subscription](https://www.openfaas.com/support/) - take a look at it with your manager? Or [at our new GitHub Sponsors program](https://github.com/sponsors/openfaas/)

End-user companies are also invited to "chop wood and carry water" - we have a huge amount of unpaid work ahead of us moving all builds off Travis and the Docker Hub, both of which are no-longer free for OSS.

**Comment by ArcticXWolf** [comment]
Sure, I'll ask 👍

**Pull request merged**
