### PR TITLE
Update chart to support IngressClass

### PR DESCRIPTION
**Pull request by wheam2002**
Signed-off-by: Sheng-Kai <wheam2002@gmail.com>

## Motivation and Context

Fixed [#895](https://github.com/openfaas/faas-netes/issues/895)
- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by LucasRoesler — APPROVED** [review]
@alexellis i tested this using 

```sh
$ helm template foo ./chart/openfaas  --set ingress.enabled="true" --set ingress.ingressClassName=bar
$ helm template foo ./chart/openfaas   --set ingress.enabled="true"
$ helm template foo ./chart/openfaas  
```

they all worked as expected.

**Comment by LucasRoesler** [comment]
@alexellis can you put this into your queue?

**Comment by sqaisar** [comment]
@alexellis @LucasRoesler 
When this issue will be released?

**Comment by LucasRoesler** [comment]
@sqaisar, @alexellis is the only one with merge permissions, but I will bring this up on the Wednesday office hours call https://github.com/openfaas/faas/issues/1683

**Comment by pype-leila** [comment]
@LucasRoesler Is there any update here?

**Comment by LucasRoesler** [comment]
@pype-leila unfortunately, i can't do anything, @alexellis is the only one that can merge this.

**Review by alexellis — APPROVED** [review]
Approved

**Pull request merged**
