### PR TITLE
Added certifier check in testing

### PR DESCRIPTION
**Pull request by zeerorg**
Signed-off-by: Rishabh Gupta <r.g.gupta@outlook.com>

## Motivation and Context
Fixes Issue #352 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Thank you for working on this PR 👍

**Comment by alexellis** [comment]
@zeerorg this PR looks good to me, however we do always need to see this field filled out:

> How Has This Been Tested?
> (empty)

**Comment by LucasRoesler** [comment]
@zeerorg Everything looks good and CI passes, but I tried running the contrib scripts locally and keep getting an error 

```
./create-kubernetes-secret.sh
error: unable to forward port because pod is not running. Current status=Pending
secret "secret-api-test-key" deleted
secret/secret-api-test-key created
```

I ran
```
./contrib/lint_chart.sh
./contrib/get_kind.sh
./contrib/create_kind_cluster.sh
./contrib/install_tiller.sh
./contrib/run_certifier.sh
```

I am running it on a Mac.

**Comment by zeerorg** [comment]
@LucasRoesler  can you get the output for 
```
export KUBECONFIG="$(kind get kubeconfig-path)"
kubectl get pods --all-namespaces
```
Also, in your listed steps you didn't run `./contrib/deploy.sh` which deploys the kubernetes cluster. Can you give it another try, with steps from `travis.yml`

**Comment by zeerorg** [comment]
@alexellis I'll add those

**Comment by LucasRoesler** [comment]
@zeerorg reading the scripts, I don't understand why deploy needs to be included. Deploy only installs openfass and `run_certifier` deletes and reinstalls the openfaas. 

I reran the steps again with `deploy` and still had the same error.

```
NAMESPACE     NAME                                         READY   STATUS             RESTARTS   AGE
kube-system   coredns-fb8b8dccf-56l5t                      1/1     Running            0          4m55s
kube-system   coredns-fb8b8dccf-vg7gq                      1/1     Running            0          4m55s
kube-system   etcd-kind-control-plane                      1/1     Running            0          3m46s
kube-system   kube-apiserver-kind-control-plane            1/1     Running            0          3m51s
kube-system   kube-controller-manager-kind-control-plane   1/1     Running            0          3m49s
kube-system   kube-proxy-l8w48                             1/1     Running            0          4m55s
kube-system   kube-scheduler-kind-control-plane            1/1     Running            0          3m59s
kube-system   tiller-deploy-6976db6745-2c4r8               1/1     Running            0          4m10s
kube-system   weave-net-vssml                              2/2     Running            0          4m55s
openfaas      alertmanager-54d8ccf44c-xvkc6                1/1     Running            0          29s
openfaas      alertmanager-645c4f7f79-s57l6                0/1     Terminating        0          82s
openfaas      faas-idler-66dcdd6945-z7w98                  1/1     Running            0          29s
openfaas      gateway-f7c8bf65d-d8vkh                      1/2     CrashLoopBackOff   1          29s
openfaas      nats-75d8f56846-5wkfx                        1/1     Running            0          29s
openfaas      prometheus-6d895bb9c9-pmk6l                  0/1     Terminating        0          82s
openfaas      prometheus-6d895bb9c9-qc5z5                  1/1     Running            0          29s
openfaas      queue-worker-64dd5b45cb-cr82j                1/1     Running            1          29s
```

It looks like the gateway crashed, it finally stabilized after the second restart

**Comment by alexellis** [comment]
@zeerorg PTAL

**Comment by LucasRoesler** [comment]
I think once it is rebased on master, it will work as expected. The issues were timing related, and those are resolved in the latest contrib scripts

**Comment by zeerorg** [comment]
Give me a bit of time I'll fix this.

**Comment by zeerorg** [comment]
Done 👍

**Comment by alexellis** [comment]
Outstanding queries on this PR. Adding label blocked until @zeerorg can spend time on it.

Please can you remove the merge commit by squashing?

**Comment by alexellis** [comment]
No action for almost a year by contributor. I'm closing this out as abandoned 😞

**Pull request closed without merging**
