### PR TITLE
Update Prometheus and AlertManager versions

### PR DESCRIPTION
**Pull request by simonpasquier**
Signed-off-by: Simon Pasquier <spasquie@redhat.com>

## Description
Bump Prometheus and AlertManager to v2.3.1 and v.015.0 respectively.

## Motivation and Context
Those versions are the current stable releases.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
@stefanprodan we are awaiting testing on this change, do you have any info on above versions?

**Comment by alexellis** [comment]
Just to be clear testing can be as simple and showing the functionality still works with your proposed versions. So in this case that means Autoscaling behaviour up and down and then the metrics.

**Comment by simonpasquier** [comment]
@alexellis thanks for the feedback, I understand completely your concerns. I'll do some testing and report here (I might be delayed a bit by other stuff).

Regarding the new versions:
* AlertManager v0.15.0 is mostly fixing bugs found in the release candidate release around the new cluster implementation.
* The main improvement for Prometheus v2.3.1 is a lower memory footprint for queries compared to v2.2.0. There hasn't been any major bug reported against this version that didn't exist in v2.2.0 too.

FYI the Prometheus team is well aware of the stability issues for 2.x and a new policy has been put in place to help with stabilizing the project.

**Comment by simonpasquier** [comment]
Here is a screenshot showing that the gateway did scale up and then down the nodeinfo function.

image

And another one showing the targets:

image

A last one for AlertManager:

image

**Comment by stefanprodan** [comment]
Thanks for testing @simonpasquier

**Comment by alexellis** [comment]
Merged. Thank you @stefanprodan for giving your input and thanks @simonpasquier for doing the due diligence, it is really the difference between being able to merge or not.

There is an opportunity to back-port your change to the Swarm OpenFaaS files too over at openfaas/faas - check out the docker-compose.yml file, or if you're not sure you want to work on that raise an issue in the repo.

👍

**Pull request merged**
