### PR TITLE
deleted duplicate mapping in operator-rbac.yaml

### PR DESCRIPTION
**Pull request by HelioStrike**
## Description

Deleted duplicate mappings in [operator-rbac.yaml](https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/templates/operator-rbac.yaml#L80).

## Motivation and Context

It is a fix for #658 .

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi thanks for your PR

You'll need to give details under "How Has This Been Tested" before we can look at it.

Alex

**Review by martindekov — COMMENTED** [review]
Hello @HelioStrike I agree there is a problem here and you commit will fix it, but can you put output of your testing or describe it first before I approve it?

**Comment by martindekov** [comment]
Also thanks for the commit on this one !

**Comment by HelioStrike** [comment]
@martindekov I'm new to the repo, was getting to know it, but don't know how to test it yet. Do you any suggestions/documentation on how I could test it?

**Comment by martindekov** [comment]
Yep you can use helm to test install the local chart on your kubernetes cluster as per the descriptions in the helm README in this repo also set `operator.create` `clusterRole` and `rbac` to true so you can reach this part of the yaml through helm.

**Comment by HelioStrike** [comment]
@martindekov I followed the setup in the helm and charts README. I pasted `operator-rbac.yaml` into `Chart.yaml`, and ran the following command:
```
helm template   openfaas chart/openfaas/   --namespace openfaas   --set basic_auth=true --set operator.create=true --set clusterRole=true --set rbac=true  --set functionNamespace=openfaas-fn > openfaas.yaml
```
gives me 
```
Error: cannot load Chart.yaml: error converting YAML to JSON: yaml: did not find expected node content
```
I can see why its happening, but how do I solve it?

**Review by alexellis — APPROVED** [review]
Looking at the diff, this seems fine so I'll merge it.

**Comment by alexellis** [comment]
Thank you @HelioStrike 

For future reference, please raise an issue before starting work on a PR, and test the solution before raising the PR

Hope to see you around again soon.

**Pull request merged**
