### PR TITLE
Proposal PR to use "helmfile"

### PR DESCRIPTION
**Pull request by Vad1mo**
I would like to get some early feedback from you guys. 
My goals are to have OpenFaaS and later OFC as Infrastructure as Code with fully automated CI/CD update/upgrade workflow.
Also, making it straight forward modifying and changing charts.

## Description
- I used Helmfile with Tillerless Helm, so people that can't use tiller will be able to use helm.
- I created a sample `helmfile.yml` providing a ready-made solution.
- Documented on how to locally develop and test charts Development-and-Testing-Charts.md
- Updated Readme to reflect the new workflow. 
  (Currently only the installation part, the rest will follow when you give a go to move forward)
- Updated templates and added function-namespace as template 
- Added basic-auth secret to template, I think it is more useful to have them in the chart as well.

## Motivation and Context
If this suits you I would like to add some **tests** so new users can test the deployment and developers can make sure their changes did mess up chart.

## How Has This Been Tested?
```sh
k3d create --name openfaas-test-helm #Create local k3s cluster in a container
export KUBECONFIG="$(k3d get-kubeconfig --name='openfaas-test-helm')" #Set kubeconfig location as environment variable
helmfile -f helmfile-local.yaml apply #Deploy current directory
helmfile -f helmfile-local.yaml test  #Test deployment directory
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
What is a helmfile? (I've not heard of it)

What is the IaaC tool you're trying to get OpenFaaS to work with btw?

**Comment by Vad1mo** [comment]
You can think of [helmfile](https://github.com/roboll/helmfile) like compose is for docker.  Having a proper helmfile setup allows me to check in my helmfile.yml and my openfaas stat in git and automate everything  with CI/CD thus enabling IaC.

**Comment by Vad1mo** [comment]
I know that there are #520, but once #520 is live I would adapt my MR so it becomes helm3 compatible.

**Comment by alexellis** [comment]
/set title: Proposal PR to use "helmfile"

**Comment by alexellis** [comment]
Please can you and @Waterdrips bring over your chat from Slack here for the community? Also whilst this helps show what you're trying to achieve, PRs shouldn't be opened with broad changes unless there's an issue first. Could you go ahead and open an issue to raise your concerns and propose your solution there? Thanks 👍 

https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md

**Comment by Waterdrips** [comment]
A summary of my points from the slack:
I am really interested in making OpenFaaS Cloud deployable in an IaC way, and changes in here are probably required.

I'm not sure that adding another dependency (helmfile) is that great, we already have the default way to install openfaas as K3sup for default installs.

Helm3 is removing the need for tiller, so the helmfile functionality with generating yaml might not be needed also?

There are a lot of updates to the docs on this pr compared with the functionality change, which makes me worried, I feel as though users who turn to the chart for 8,instalation rather than k3sup are probably ok with the installation? 

I'm very interested in getting some more tests written around the chart as you have mentioned, it might be better to add these in before trying to change too much - I'm happy to help with this as it was on my list of things to look at!

**Comment by Vad1mo** [comment]
Helmfile by itself isn't exclusive. People who don't want to use Helmfile don't need to. 
An option would be to add a section in the docs mentioning the installation with the Helmfile. This would make Helmfile an optional requirement. What do you think @alexellis @Waterdrips ?

With Helmfile there are only two steps in the [install instruction] (https://github.com/Vad1mo/faas-netes/tree/master/chart/openfaas#install) (1. Set password 2. Helmfile apply) vs. five with helm only.

**My Conclusions**
* I am going to break this PR down to multiple smaller PRs avoiding too many changes at once. 
  1. Change Chart
  2. Add Helmfile as an optional requirement
  3. Add Automated Tests.

Happy to see that you positive towards Helmfile. I guess some more highlights would help to see the benefits.

**Comment by Waterdrips** [comment]
I think it would be good to have an issue raised for each of these, then we can track/discuss on those individually?

**Comment by alexellis** [comment]
I'm going to close this PR, but it's not the end of the discussion. We're just going to try to follow the process outlined in the community guide. I hope that's OK with everyone who's interested. See you on #551. 

For any queries on the process, please see the contributing guide - https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md

**Comment by zpratt** [comment]
In case anyone landed on this looking for a helmfile example, I've written a short guide: https://github.com/zpratt/local-openfaas-workbench

If the maintainers think this would be useful, I'd be happy to contribute an example to the docs, otherwise this can remain a reference for those who wish to use helmfile.

**Pull request closed without merging**
