### PR TITLE
Update armhf configuration to match x86

### PR DESCRIPTION
**Pull request by ericstoekl**
## Description

This change copies in the latest version of the `yaml/` directory into the `yaml_armhf/` directory, overwriting all files. The `image:` tag is then changed to our latest arm-compatible versions.

Note -- the `faasnetesd` armhf build image needs to be updated in the official Docker Hub repo. This change uses my own built image, which will need to be changed to the official image before this is merged.

## Motivation and Context

- [X] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
https://github.com/openfaas/faas-netes/issues/152

## How Has This Been Tested?

Tested that the following works, with success:

- async invocation
- auto-scaling
- prometheus
- function store
 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
@ericstoekl I'll get an image ready please change the tags to `0.4.5-armhf`

**Comment by alexellis** [comment]
Curious.. how long did your build of faas-netesd take on ARM?

**Comment by ericstoekl** [comment]
Updated to the official version of `faas-netes`. This is ready to merge.

Build takes 10 minutes with `--no-cache` on the rpi3.

**Comment by alexellis** [comment]
@ericstoekl there must be something out of sync between your PR and local environment because I can't get OpenFaaS to work @stefanprodan is also having issues. This is the error - please can you look into it?

```
NAME                            READY     STATUS                       RESTARTS   AGE
alertmanager-59f64fb5d4-z78p4   0/1       CreateContainerConfigError   0          1h
faas-netesd-7db4d57c98-6shft    1/1       Running                      0          1h
gateway-79c7fcd99b-6mlfn        1/1       Running                      0          1h
nats-6c4f7df-w6zbt              1/1       Running                      0          1h
prometheus-79fc6c7566-mcc44     0/1       CreateContainerConfigError   0          1h
queue-worker-9c6d8d896-p5kkz    1/1       Running                      0          1h
```

**Comment by alexellis** [comment]
Stefan mentioned there is an issue with 1.9.4 so I'm creating my cluster with 1.9.2 and then I'll test again, but to have parity (what this PR was for) we really need to have the same Prometheus version. I don't think the configuration is compatible with 1.5

https://github.com/kubernetes/kubernetes/issues/61076

**Pull request merged**
