### PR TITLE
Update manifests to use correct apis for Kubernetes 1.16

### PR DESCRIPTION
**Pull request by carlosedp**
## Description

Update manifests to support new API versions on Kubernetes 1.16

## Motivation and Context

Fixes https://github.com/openfaas/faas-netes/issues/510 and allows deploying on Kubernetes 1.16.

## How Has This Been Tested?

Deployed on a 1.16 cluster.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
@carlosedp FYI everything in the YAML folders is generated, we need to update the templates, then run `make charts`. Please don't commit the effect of `make charts`, but just update the templates in chart/openfaas/

**Comment by carlosedp** [comment]
Done!

**Comment by alexellis** [comment]
https://github.com/openfaas/faas-netes/pull/515#issuecomment-533717061

It is important that only one person runs and commits the changes of `make charts`, but you can use it for testing locally.

Please can you reset these commits and only update the charts/openfaas folder? We'll do the rest.

**Comment by carlosedp** [comment]
My bad, just updated with correct changes.

**Pull request merged**
