### PR TITLE
Remove confusing armhf references from helm chart

### PR DESCRIPTION
**Pull request by alexellis**
Signed-off-by: Alex Ellis <alexellis2@gmail.com>

## Description

Removes armhf from helm chart. To use this architecture please make use of the plain YAML files in /yaml_armhf.

## Motivation and Context

Reasoning: no official Kubernetes tiller server-image.

## How Has This Been Tested?

tbd

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by rimusz** [comment]
@alexellis chart version needs to bumped up on every change to chart

**Comment by alexellis** [comment]
👍

**Comment by rimusz** [comment]
LGTM

**Comment by alexellis** [comment]
Yes this needs rebasing or doing fresh.

**Comment by alexellis** [comment]
Closing as there is an issue with the Kubernetes engine right now preventing testing.

**Pull request closed without merging**
