### PR TITLE
use openFaasImagePullPolicy for faas-netes container (and not faasnet…

### PR DESCRIPTION
**Pull request by swachter**
## Description
The faas-netes container uses the wrong imagePullPolicy it should use openFaasImagePullPolicy and not faasnetesd.imagePullPolicy

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by swachter** [comment]
> 
> 
> This doesn't look right.

From the documentation of the helm chart:

| Parameter               | Description                           | Default                                                    |
| ----------------------- | ----------------------------------    | ---------------------------------------------------------- |
| `faasnetesd.imagePullPolicy` | Image pull policy for deployed functions | `Always` |
| `openfaasImagePullPolicy` | Image pull policy for openfaas components, can change to `IfNotPresent` in offline env | `Always` |

The gateway pod with its gateway and faas-netes containers are a openfaas component, i.e. their image pull policy should be set by `openfaasImagePullPolicy`. On the other hand the `faasnetesd.imagePullPolicy` setting is used to set the environment variable image_pull_policy that in turn is considered by the two mentioned containers.

**Comment by alexellis** [comment]
You're right, but perhaps the issue here is that the naming is really confusing. Can we do better? @LucasRoesler @stefanprodan 

Btw you have a rebase conflict on this PR.

Alex

**Comment by alexellis** [comment]
Derek close: invalid PR

**Comment by alexellis** [comment]
Derek add label: invalid

**Comment by alexellis** [comment]
Hi Stefan,

I'm going to close this PR. Please raise a new PR from a fresh branch, I don't want to see a merge commit in the history. You should do a rebase into your fork if you're out of date.

I think we also need to go back to the main issue and detail the solution properly before working on it.

The pull policy defined here doesn't line up with the README or the proposed change from what I can see.

```
faasnetes:
  image: openfaas/faas-netes:0.7.0
  readTimeout : "60s"
  writeTimeout : "60s"
  imagePullPolicy : "Always"    # Image pull policy for deployed functions
```

Alex

**Pull request closed without merging**
