### PR TITLE
Helm chart: bump operator version to 0.9.7

### PR DESCRIPTION
**Pull request by stefanprodan**
## Description

- bump openfaas-operator version to 0.9.7 
- reuse faas-netes env vars for the operator

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

Tested locally with Kubernetes Kind and kubesec as described [here](https://github.com/openfaas-incubator/openfaas-operator/pull/83)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @stefanprodan, unfortunately I merged another PR that changed the charts and the chart version so you need to do a rebase before I can merge this.

Alex

**Comment by alexellis** [comment]
Sorry I still see `This branch cannot be rebased due to conflicts`

Since your changes are so minimal, can you stash them and overlay them on origin/master and push up a new branch? I think it'll be quicker / easier

**Comment by stefanprodan** [comment]
Try refreshing the page, I don't see any conflicts.

**Comment by alexellis** [comment]
Screenshot 2019-06-16 at 09 36 33

Sorry, git can be a pain.

**Pull request closed without merging**
