### PR TITLE
Running faas-netes in the same pod as the gateway, exposed on port 8081

### LINKED ISSUE #189: Research: Run faas-netes in gateway pod as a side-car
We could run the faas-netes container in the Pod used for the gateway (as a side-car)

This is what we're doing with the new CRD. It means there will be a 1-1 relationship between gateways and faas-netes.

### PR DESCRIPTION
**Pull request by rawkode**
Closes #189

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

#189 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
> How Has This Been Tested?

(empty)

A change like this would need testing including some edge cases and increased load testing.

**Comment by alexellis** [comment]
PR looks as expected, but it needs end-to-end testing before it can be merged.

**Comment by alexellis** [comment]
Seems like @rawkode has been on honey-moon - if anyone wants to help test/validate this change then it would be good to merge for performance.

**Comment by rawkode** [comment]
I'm running tests of using test-kitchen and ServerSpec to confirm that changes to faas-netes work. Should be ready today

**Comment by alexellis** [comment]
I just noticed that as well as the rebase being needed - this change also doesn't appear to cover the plain YAML files in ./yaml

**Comment by rawkode** [comment]
I closed this because the rebase was a major pain. Replaced with:

https://github.com/openfaas/faas-netes/pull/225

**Pull request closed without merging**
