### PR TITLE
README: Fix code blocks in helm template section

### PR DESCRIPTION
**Pull request by nlochschmidt**
Just a minor change to the helm chart documentation

### CODE REVIEW

**Comment by nlochschmidt** [comment]
Just saw that you don't want PRs for doc fixes. Sorry about that.

**Comment by alexellis** [comment]
Hi, thanks for your PR. 

No, the contribution guide says: not for typos - it doesn't say "not for changes to documentation". It's easier for us to cover them then to teach people the contribution process. 

If you can sign off your commit with the instructions from Derek I'll review it and merge it if renders correctly.

**Comment by nlochschmidt** [comment]
Thanks for clarifying. I've reopened the MR and force pushed the commit, this time with sign-off

**Comment by alexellis** [comment]
I'm going to merge the PR, but I can't see what it fixes? The README file renders correctly and `sh` blocks don't have very useful highlighting anyway before/after?

**Comment by alexellis** [comment]
Unless I've missed something, then it's exactly the same visually and "fixes" nothing.

Screenshot 2019-07-27 at 11 58 56

I am OK with PRs for the sake of PRs, but the language could be better for the next one.

**Comment by nlochschmidt** [comment]
@alexellis, I wonder how I missed both of your replies 🤔. Sorry about the wording, will do better next time 👍. 
The main change was actually the code block under **3. Install the components using kubectl** which wasn't there before.

Before:

Bildschirmfoto 2019-08-19 um 20 51 52

After:

Bildschirmfoto 2019-08-19 um 20 52 17

**Pull request merged**
