### PR TITLE
Use k8s.io/api/apps instead of k8s.io/api/extensions

### PR DESCRIPTION
**Pull request by stefanprodan**
Fix: #444 

## Description

Use the same Kubernetes API for Deployment kind as in openfaas-operator.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

Tested locally with Kubernetes Kind

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
👏 👏 👏 

What's the impact to existing users @stefanprodan ?

What if I upgrade my cluster to the new version of faasnetes and have functions deployed?

Alex

**Comment by alexellis** [comment]
Can you push up your own image somewhere?

**Comment by stefanprodan** [comment]
@alexellis the image is at `stefanprodan/faas-netes:appsv1`

**Comment by stefanprodan** [comment]
This should have no impact for users running on Kubernetes >= 1.8

**Comment by alexellis** [comment]
Please can you confirm, then I'll merge based upon your results.

1) setup the cluster (use the kind dev scripts if you like)
2) deploy a function
3) invoke it
4) edit to the `stefanprodan/faas-netes:appsv1` image`
5) try to invoke the function, then delete it
6) try to deploy a new function

That'd be great.. thanks 👍

**Comment by stefanprodan** [comment]
Deploy and invoke works fine but listing doesn't return the newly deployed functions. 

I've deployed nodeinfo from the UI but I'm getting:

```
faas-cli list
Function                      	Invocations    	Replicas
echo                          	4              	1   
```

But nodeinfo can be invoked and described:

```
faas-cli describe nodeinfo
Name:                nodeinfo
Status:              Ready
Replicas:            1
Available replicas:  1
Invocations:         0
Image:               functions/nodeinfo:latest
Function process:    
URL:                 http://localhost:31112/function/nodeinfo
Async URL:           http://localhost:31112/async-function/nodeinfo
Annotations:         prometheus.io.scrape : false
```

**Comment by stefanprodan** [comment]
@alexellis I've found the problem, in extensions API the label selector was ignored. I've removed the selector and now faas-netes works like before.

```
faas-cli list
Function                      	Invocations    	Replicas
certinfo                      	1              	1    
nodeinfo                      	4              	1    
nslookup                      	0              	1    
```

**Comment by alexellis** [comment]
👍 What if you create a random (not openfaas) deployment? Does it list that too?

Alex

**Comment by stefanprodan** [comment]
@alexellis check again please, I've added that label to deployments.

**Comment by alexellis** [comment]
Which docker image `stefanprodan/faas-netes:appsv1-v3`?

I haven't run the code, it was just a question.

**Comment by alexellis** [comment]
I'm getting the following error:

```
2019/06/06 17:10:09 deployments.apps is forbidden: User "system:serviceaccount:openfaas:faas-controller" cannot list resource "deployments" in API group "apps" in the namespace "openfaas-fn"
```

**Comment by stefanprodan** [comment]
Run helm upgrade to apply the RBAC from this branch.

**Comment by stefanprodan** [comment]
@alexellis the image is `stefanprodan/faas-netes:appsv1-v4`

**Comment by alexellis** [comment]
So is the only breaking change the RBAC?

I can see users taking this version and being really confused, in the worst case - frustrated. How can we manage that and prepare for it ahead of time?

**Comment by alexellis** [comment]
https://github.com/openfaas/faas-netes/commit/70c36b978dd7daf451f116409fef684f44f9e278

**Pull request merged**
