### PR TITLE
Add http timeouts for functions

### LINKED ISSUE #28: Enable variable timeouts for HTTP
This matches the API gateway in the faas repo:

```
read_timeout - seconds as an integer
write_timeout - seconds as an integer
```

The code can be copied from read_config.go

### PR DESCRIPTION
**Pull request by e-beach**
Signed-off-by: Elliott Beach elliot2.71828@gmail.com

Fixes #28

I'll add this as I work on it as @alexellis is concerned about getting it done.
Still needs to be tested as per https://github.com/openfaas/faas/pull/96.

### CODE REVIEW

**Comment by e-beach** [comment]
Yes, also should we be logging the timeout as in https://github.com/openfaas/faas/pull/96?

**Comment by alexellis** [comment]
Matching the gateway sounds good

**Comment by e-beach** [comment]
@alexellis Should logging code go in this module or faas-provider which actually starts the server? The latter would be more consistent with the gateway logging. 

Also, currently working on testing logs.

**Comment by alexellis** [comment]
Good point. Let's start by getting it in here so we can wrap up the PR.

**Comment by e-beach** [comment]
Yes, working on testing local image via kubernetes, which will just need a little more reading on my part.

**Comment by e-beach** [comment]
Update, figured out how to update the docker image. I'm working on modifying the faas-cli functions, so I can test with a slow function. Future PRs will by me will hopefully go through faster with this base knowledge.

**Comment by alexellis** [comment]
@e-beach a slow function could be alpine base image with fprocess="sleep 10" for instance. 

Glad to hear you're getting the hang of the process now 👍 we have a conflict on the server.go file since release 0.3 where I moved the files to the "openfaas" org. Also please check RE: DCO sign-off on every commit.

**Comment by e-beach** [comment]
OK, finally got this!! 
The API responds with `502` bad gateway when the function times out. Should this be a 504 error?

Also, #96 didn't mention how to handle testing the `read_timeout`. It appears that they didn't test read (client-side) timeout, so I haven't either. Will work on fixing conflicts / signing.

@alexellis sorry for missing your ping!

**Comment by e-beach** [comment]
History is borked, will fix tomorrow

**Comment by e-beach** [comment]
@alexellis This should be good now. I still have the question about it giving a 502 error when 504 would be more appropriate for timing out, but that will be addressed in openfaas/faas.

**Comment by alexellis** [comment]
Good question @e-beach - you have a third timeout set on the function - `hard_timeout` - this is where the watchdog steps in and kills the process.

**Comment by alexellis** [comment]
I think a correct HTTP timeout code would be awesome, but in a separate PR + issue. Do you want to raise it?

**Comment by alexellis** [comment]
LGTM, merged and thanks for sticking with it 💯

**Pull request merged**
