### PR TITLE
Expose nats monitoring metrics to prometheus

### PR DESCRIPTION
**Pull request by matthiashanel**
## Description

This fixes https://github.com/openfaas/nats-queue-worker/issues/99

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
Issue was raised in nats-queue-worker repo.

## How Has This Been Tested?

* Started openfaas in my minikube environment
* Forwarded the prometheus port using `kubectl port-forward svc/prometheus -n openfaas 31111:9090`
* For testing purposes invoked asynchronous functions.
* took screen shots of prometheus ui 

depicting newly exposed metrics:
Screen Shot 2020-05-19 at 6 17 44 PM

metric as suggested in https://docs.nats.io/nats-streaming-concepts/monitoring
Screen Shot 2020-05-19 at 6 29 55 PM

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @matthiashanel, thank you for making the PR, (if I remember correctly, it's usually the team-members that cover the Kubernetes side of things)

What you've edited is our generated YAML files, so they will get overwritten each time we generate a chart with `make charts`.

You'll need to edit the files in ./chart/openfaas/templates instead, but it should be a similar change, once made, either deploy the chart using the local instructions in the chart README, or run `make charts` (don't commit the changes from this step) and then try to apply the YAML files again.

Chart README for local testing -> https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/README.md

Templates for Helm chart -> https://github.com/openfaas/faas-netes/tree/master/chart/openfaas/templates

Makefile target -> https://github.com/openfaas/faas-netes/blob/master/Makefile#L30

Let me know if you have any questions.

**Comment by matthiashanel** [comment]
@alexellis I reverted my original change and changed the helm templates instead. 
Changed the readme as well. 

Generated the yaml files with nats.metrics.enabled=true and nats.metrics.enabled=false
```
helm template openfaas chart/openfaas --namespace openfaas --set nats.metrics.enabled=true  > openfaas.yaml
```
Generated yaml files look as expected.
I re ran my tests for the enabled case. works like a charm.

**Comment by alexellis** [comment]
This is awesome, thank you so much 🎉

This is on my list to look at next (and to try)

Would you be open to adding the flag to enable this to the OpenFaaS arkade app? It's simple Go + Cobra.

I'm not too familiar with the specific metrics, do you think it would be useful to have a note in the OpenFaaS docs on the metrics page?

**Comment by alexellis** [comment]
One concern here is that the image doesn't have multi-arch support (NATS does though), so we must make sure ARM and ARM64 users don't opt into using the metrics add-on. This would have crashed the Pod for those users, so I think we made the right choice in making this off by default.

https://hub.docker.com/r/synadia/prometheus-nats-exporter/tags

**Comment by alexellis** [comment]
For the time being this can be tested using:

```bash
arkade install openfaas --set nats.metrics.enabled=true
```

Generating:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: null
  generation: 1
  labels:
    app: openfaas
    chart: openfaas-5.8.3
    component: nats
    heritage: Helm
    release: openfaas
    manager: kube-controller-manager
    operation: Update
    time: "2020-05-22T09:14:33Z"
  name: nats
  selfLink: /apis/apps/v1/namespaces/openfaas/deployments/nats
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nats
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io.port: "7777"
        prometheus.io.scrape: "true"
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: nats
    spec:
      containers:
      - args:
        - --store
        - memory
        - --cluster_id
        - faas-cluster
        - -m
        - "8222"
        command:
        - /nats-streaming-server
        image: nats-streaming:0.17.0
        imagePullPolicy: IfNotPresent
        name: nats
        ports:
        - containerPort: 4222
          protocol: TCP
        resources:
          requests:
            memory: 120Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - -port
        - "7777"
        - -connz
        - -routez
        - -subz
        - -varz
        - -channelz
        - -serverz
        - http://localhost:8222
        image: synadia/prometheus-nats-exporter:0.6.2
        imagePullPolicy: IfNotPresent
        name: metrics
        ports:
        - containerPort: 7777
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

**Comment by alexellis** [comment]
Metrics being collected: :tada: 

prom

**Pull request merged**
