### PR TITLE
[WIP] Bump alertmanager / Prometheus to RC

### PR DESCRIPTION
**Pull request by alexellis**
Signed-off-by: Alex Ellis (VMware) alexellis2@gmail.com <alexellis2@gmail.com>

## Description

Bump alertmanager / Prometheus to RC version to fix alert bug with AlertManager

## Motivation and Context

Issue found with AlertManager 

Reported by @stefanprodan. Stefan please can you link to the issue you found?

## How Has This Been Tested?

Tested on Swarm, replicated to Kubernetes - needs to be tested via Helm and kubectl.

Test criteria - check that scaling up/down still works.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] I have signed-off my commits with `git commit -s`
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Tested with plain YAML, just needs testing with helm now.

**Comment by stefanprodan** [comment]
https://github.com/prometheus/prometheus/issues/3543

**Comment by ericstoekl** [comment]
I am testing this on Azure AKS and I am not seeing a test function auto-scale when it is hit with many requests. I use this command to load test it:

```
ab -p empty -n 500 -c 10 $gw/function/nodeinfo
```

It sends a POST with empty body to the sample `nodeinfo` function which is deployed from the store. When using the current `master` branch of faas-netes, I see the function auto-scale to a 20 replicas when I run the `ab` command. With this update, I don't see it ever scale up.

I reverted [this line](https://github.com/openfaas/faas-netes/pull/158/files#diff-84c4c0a5fa403e2d4efd60cd2a92e474R31) in the PR code and scaling works. I suspect an issue with the `prom/alertmanager:v0.15.0-rc.0` image.

**Comment by alexellis** [comment]
Fixed in #170 - helm still needs updating if @ericstoekl or @stefanprodan would like to do that?

**Comment by tranotheron** [comment]
I'm on it

**Pull request closed without merging**
