### PR TITLE
Set function namespace during yaml generation

### PR DESCRIPTION
**Pull request by LucasRoesler**
## Description

- Set the function namespace when using `helm template` in the
`create-static-manifest` script.  Allow overriding this value as the 5th
argument, using `openfaas-fn` as the default.
- Added additional documentation to the `create-static-manifest` script
- Add a line to the yaml/README.md to note that the files are generated
- Add gitattributes folder to let github also know that the folder is
generated
-  This is needed to preserve the original configuration from prior to
the introduction of the `create-static-manifest` in #424

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

Resolves #430

## How Has This Been Tested?

The correct namespace was validated by reviewing the new yaml files

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Thank you Lucas

**Comment by alexellis** [comment]
Can you merge the PR with the rebase button?

**Comment by LucasRoesler** [comment]
I can not 

image

**Comment by alexellis** [comment]
Ok so looks like you can push to remote branches and merge into non-master but not merge into master.

**Comment by alexellis** [comment]
:+1: thank you for the quick fix

**Pull request merged**
