### PR TITLE
Add parameter for signing key secret used by dashboard

### PR DESCRIPTION
**Pull request by welteki**
## Description

Add a helm parameter `dashboard.signingKeySecret` to select the signing keys secret for the dashboard.

Impact: Users currently using the dashboard in staging or production will have to set the `dashboard.signingKeySecret` parameter to select their current signing key secret.

## Why is this needed?

Allows users to select the secret with the signing keys or leave blank to have the keys generated automatically by the dashboard.

## Who is this for?

What company is this for? Are you listed in the [ADOPTERS.md](https://github.com/openfaas/faas/blob/master/ADOPTERS.md) file?

## How Has This Been Tested?

Used the chart to deploy the dashboard both with and without the `dashboard.signingKeySecret` parameter set and verified the dashboard-jwt volume is only mounted when the parameter is set.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
@welteki what is left before WIP can be taken off this PR?

**Comment by welteki** [comment]
> @welteki what is left before WIP can be taken off this PR?

I was waiting for the release of the new dashboard image. The image version has been upgraded now and I removed the WIP status.

**Review by alexellis — APPROVED** [review]
Approved

**Comment by alexellis** [comment]
@welteki I've published 0.2.0 so we should be fine now?

**Pull request merged**
