### PR TITLE
Feature implement logs provider

### PR DESCRIPTION
**Pull request by LucasRoesler**
## Description
This creates a new logs endpoint that works with the new faas-provider interface the http request to the log provider as described in openfaas/faas#751 and openfaas/faas-provider#15

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

See openfaas/faas#751
and openfaas/faas#1130
and openfaas/faas-provider#15

## How Has This Been Tested?

This has been manually tested so far, i plan to write some integration tests because i think that mocking the k8s server will be too complicated in this case

This can be tested manually using 3 terminal 

```sh
## Terminal 1
make start-kind
make build && kind load docker-image openfaas/faas-netes:latest

export KUBECONFIG=$(kind get kubeconfig-path --name="${OF_DEV_ENV:-kind}")

helm upgrade openfaas --install ./chart/openfaas \
    --namespace openfaas  \
    --set basic_auth=true \
    --set openfaasImagePullPolicy=IfNotPresent \
    --set faasnetes.imagePullPolicy=IfNotPresent \
    --set faasnetes.image=openfaas/faas-netes:latest \
    --set functionNamespace=openfaas-fn

bash ./contrib/restart_port_forward.sh
kubectl -n openfaas port-forward deploy/gateway 8081

## Terminal 2
curl  -H "Connection: keep-alive" "http://localhost:8081/system/logs?name=echo&follow=true"

## Terminal 3
cat password.txt | faas-cli login --gateway=http://localhost:31112 -u admin -s
echo "`date`"  | faas-cli invoke echo --gateway=http://localhost:31112
```
In Terminal 2, you will see 2 log lines per request in terminal 3.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
@stefanprodan thanks for reviewing the code, did you test the PR e2e?

**Comment by alexellis** [comment]
@LucasRoesler do we have a dependent faas-provider to merge before this?

**Comment by alexellis** [comment]
Some inconsistency in behaviour between scaling to zero and opening a connection with zero replicas established. What are your thoughts?

1)

* Run curl to get logs for 1/1 pod
* Scale deployment to 0
* curl hangs / connection remains open

```
curl  -H "Connection: keep-alive" "http://localhost:8081/system/logs?name=echo&follow=true"
{"name":"echo","instance":"echo-68789744-rdfqp","timestamp":"2019-06-11T11:19:50.047302098Z","text":"2019/06/11 11:19:50 Forking fprocess.\n"}
{"name":"echo","instance":"echo-68789744-rdfqp","timestamp":"2019-06-11T11:19:50.049406556Z","text":"2019/06/11 11:19:50 Wrote 4 Bytes - Duration: 0.002018 seconds\n"}






{"name":"echo","instance":"echo-68789744-rdfqp","timestamp":"2019-06-11T11:20:42.768908241Z","text":"2019/06/11 11:20:42 SIGTERM received.. shutting down server in 5s\n"}
{"name":"echo","instance":"echo-68789744-rdfqp","timestamp":"2019-06-11T11:20:42.768958782Z","text":"2019/06/11 11:20:42 Removing lock-file : /tmp/.lock\n"}

{"name":"echo","instance":"echo-68789744-rdfqp","timestamp":"2019-06-11T11:20:47.77106144Z","text":"2019/06/11 11:20:47 No new connections allowed. Exiting in: 5s\n"}


^C
```

2)

* After having run scale to zero replicas
* Run curl
* See error

```
curl  -H "Connection: keep-alive" "http://localhost:8081/system/logs?name=echo&follow=true"
function log request failed
```

**Comment by alexellis** [comment]
I ran this, whilst scaling to zero and the container is clearly up but I still see no output:

```
curl  -H "Connection: keep-alive" "http://localhost:8081/system/logs?name=echo&follow=true"



```

When when I invoked the function I got this:

```
curl  -H "Connection: keep-alive" "http://localhost:8081/system/logs?name=echo&follow=true"




curl: (18) transfer closed with outstanding read data remaining
```

Reconnecting I got this:

```
curl  -H "Connection: keep-alive" "http://localhost:8081/system/logs?name=echo&follow=true"
{"name":"echo","instance":"echo-68789744-2mb4b","timestamp":"2019-06-11T11:23:28.852577475Z","text":"2019/06/11 11:23:28 Version: 0.13.0\tSHA: fa93655d90d1518b04e7cfca7d7548d7d133a34e\n"}
{"name":"echo","instance":"echo-68789744-2mb4b","timestamp":"2019-06-11T11:23:28.852615681Z","text":"2019/06/11 11:23:28 Read/write timeout: 5s, 5s. Port: 8080\n"}
{"name":"echo","instance":"echo-68789744-2mb4b","timestamp":"2019-06-11T11:23:28.852619868Z","text":"2019/06/11 11:23:28 Writing lock-file to: /tmp/.lock\n"}
{"name":"echo","instance":"echo-68789744-2mb4b","timestamp":"2019-06-11T11:23:28.852622429Z","text":"2019/06/11 11:23:28 Metrics server. Port: 8081\n"}
{"name":"echo","instance":"echo-68789744-2mb4b","timestamp":"2019-06-11T11:24:33.707306961Z","text":"2019/06/11 11:24:33 Forking fprocess.\n"}
{"name":"echo","instance":"echo-68789744-2mb4b","timestamp":"2019-06-11T11:24:33.708715287Z","text":"2019/06/11 11:24:33 Wrote 4 Bytes - Duration: 0.001354 seconds\n"}

```

**Comment by alexellis** [comment]
Then I scaled from 1/1 to 2/2, but I got no output about the watchdog starting up?

```
 kubectl scale deploy/echo --replicas=2 -n openfaas-fn
deployment.extensions/echo scaled
```

All I see is the output from the first container:

```
curl  -H "Connection: keep-alive" "http://localhost:8081/system/logs?name=echo&follow=true"
{"name":"echo","instance":"echo-68789744-2mb4b","timestamp":"2019-06-11T11:23:28.852577475Z","text":"2019/06/11 11:23:28 Version: 0.13.0\tSHA: fa93655d90d1518b04e7cfca7d7548d7d133a34e\n"}
{"name":"echo","instance":"echo-68789744-2mb4b","timestamp":"2019-06-11T11:23:28.852615681Z","text":"2019/06/11 11:23:28 Read/write timeout: 5s, 5s. Port: 8080\n"}
{"name":"echo","instance":"echo-68789744-2mb4b","timestamp":"2019-06-11T11:23:28.852619868Z","text":"2019/06/11 11:23:28 Writing lock-file to: /tmp/.lock\n"}
{"name":"echo","instance":"echo-68789744-2mb4b","timestamp":"2019-06-11T11:23:28.852622429Z","text":"2019/06/11 11:23:28 Metrics server. Port: 8081\n"}
{"name":"echo","instance":"echo-68789744-2mb4b","timestamp":"2019-06-11T11:24:33.707306961Z","text":"2019/06/11 11:24:33 Forking fprocess.\n"}
{"name":"echo","instance":"echo-68789744-2mb4b","timestamp":"2019-06-11T11:24:33.708715287Z","text":"2019/06/11 11:24:33 Wrote 4 Bytes - Duration: 0.001354 seconds\n"}
```

Then I gave this error a few seconds later:

```

curl: (18) transfer closed with outstanding read data remaining
```

**Comment by alexellis** [comment]
Running the command a second time gave the expected output, so it seems like there may be an issue with the watch group / concurrency or informer?

```
curl  -H "Connection: keep-alive" "http://localhost:8081/system/logs?name=echo&follow=true"
{"name":"echo","instance":"echo-68789744-2mb4b","timestamp":"2019-06-11T11:23:28.852577475Z","text":"2019/06/11 11:23:28 Version: 0.13.0\tSHA: fa93655d90d1518b04e7cfca7d7548d7d133a34e\n"}
{"name":"echo","instance":"echo-68789744-2mb4b","timestamp":"2019-06-11T11:23:28.852615681Z","text":"2019/06/11 11:23:28 Read/write timeout: 5s, 5s. Port: 8080\n"}
{"name":"echo","instance":"echo-68789744-2mb4b","timestamp":"2019-06-11T11:23:28.852619868Z","text":"2019/06/11 11:23:28 Writing lock-file to: /tmp/.lock\n"}
{"name":"echo","instance":"echo-68789744-2mb4b","timestamp":"2019-06-11T11:23:28.852622429Z","text":"2019/06/11 11:23:28 Metrics server. Port: 8081\n"}
{"name":"echo","instance":"echo-68789744-2mb4b","timestamp":"2019-06-11T11:24:33.707306961Z","text":"2019/06/11 11:24:33 Forking fprocess.\n"}
{"name":"echo","instance":"echo-68789744-2mb4b","timestamp":"2019-06-11T11:24:33.708715287Z","text":"2019/06/11 11:24:33 Wrote 4 Bytes - Duration: 0.001354 seconds\n"}
{"name":"echo","instance":"echo-68789744-cklnt","timestamp":"2019-06-11T11:25:07.920084909Z","text":"2019/06/11 11:25:07 Version: 0.13.0\tSHA: fa93655d90d1518b04e7cfca7d7548d7d133a34e\n"}
{"name":"echo","instance":"echo-68789744-cklnt","timestamp":"2019-06-11T11:25:07.92012928Z","text":"2019/06/11 11:25:07 Read/write timeout: 5s, 5s. Port: 8080\n"}
{"name":"echo","instance":"echo-68789744-cklnt","timestamp":"2019-06-11T11:25:07.920133901Z","text":"2019/06/11 11:25:07 Writing lock-file to: /tmp/.lock\n"}
{"name":"echo","instance":"echo-68789744-cklnt","timestamp":"2019-06-11T11:25:07.920136596Z","text":"2019/06/11 11:25:07 Metrics server. Port: 8081\n"}

```

Test case:

* Connect to view logs with 1/1
* Scale to 2/2
* Should see the 2nd watchdog output as it starts up

**Comment by alexellis** [comment]
```
{"name":"echo","instance":"echo-68789744-2mb4b","timestamp":"2019-06-11T11:27:59.848294044Z","text":"2019/06/11 11:27:59 Wrote 0 Bytes - Duration: 0.007418 seconds\n"}
```

In the timestamp, is it normal practice to have such as verbose tick/sub-second value?

```
2019-06-11T11:27:59.848294044Z
```

**Comment by alexellis** [comment]
I'm getting the connection close on me when I use `follow=true&tail=40`, what would you expect to happen here?

**Comment by LucasRoesler** [comment]
> I'm getting the connection close on me when I use `follow=true&tail=40`, what would you expect to happen here?

This behavior comes from the `faas-provider` handler implementation.  From when it was originally called `limit` instead of `tail`; see https://github.com/openfaas/faas-provider/pull/15/files#diff-46a528fd5d295f6ca4aaf93db323005eR98 

The behavior in `kubectl` is to start and follow the logs starting from `tail` lines from the end,  meaning it prints the last `tail` lines and then follows for more.  From the provider's perspective, i am not sure we can promise the "return the last `tail` lines of the logs", this will be very dependent on the underlying provider to support this behavior.   Both swarm and k8s apis support this.   Loki does not explicitly define a tail, instead is always assumes that you want to read logs from the tail, at least according to this doc https://github.com/grafana/loki/blob/master/docs/api.md  

Since we removed `limit` from the provider spec, I think this limit statement https://github.com/openfaas/faas-provider/pull/15/files#diff-46a528fd5d295f6ca4aaf93db323005eR98  should be removed and allow the underlying log system to handle the `tail` value directly, the faas-provider can't do anything directly with the value

**Comment by LucasRoesler** [comment]
@alexellis please look at the last two commits on this PR in the provider https://github.com/openfaas/faas-provider/pull/15  The first fixes the curl error, 

```
curl: (18) transfer closed with outstanding read data remaining
```

I had originally fixed this in the hijacker implementation.  The docs for the http response writer implied that this wasn't needed for the flusher, but clearly it is. 

The second commit removes the line limit behavior, because i don't think it matches what you wanted for the `tail` option.  As I noted in https://github.com/openfaas/faas-netes/pull/388#issuecomment-500841281, the tail behavior will be provider dependent but should be available in our intended log providers.

**Pull request merged**
