### PR TITLE
Add NATS Streaming maximum payload option to helm chart

### PR DESCRIPTION
**Pull request by CarbonC**
Add NATS Streaming maximum payload option to helm chart

## Description
Add NATS Streaming maximum payload option to helm chart. The default is the same as the current one, 1Mb.

## Motivation and Context
It allows people who need to pass a variable to set the nats config max payload size. This allow to potentially do async request of more than 1Mb if configured, or to have a stricter limit.
Fixes https://github.com/openfaas/faas-netes/issues/734
- [X] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
Tested on a cluster setup with arkade and no costumisation, then updated with helm upgrade to test different payload size. Sent different payload to verify that the limit was correctly applied.
NB: you have to increase nginx max request size too if you dont want your request to be stopped before reaching nats.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by CarbonC** [comment]
I didnt run make charts since it looks like to be likely to provoke conflicts. Tell me if anything else is needed!

**Comment by alexellis** [comment]
My concern here is that you may be using NATS inappropriately where you should be using Minio or S3 to store your uploads before fetching them in a function.

Changing these kinds of default values can create unexpected side-effects and issues for us when we have to support this change for the community.

I would ask you to please elaborate on the problem you're trying to solve in the issue you raised.

Alex

**Comment by CarbonC** [comment]
> My concern here is that you may be using NATS inappropriately where you should be using Minio or S3 to store your uploads before fetching them in a function.
> 
> Changing these kinds of default values can create unexpected side-effects and issues for us when we have to support this change for the community.
> 
> I would ask you to please elaborate on the problem you're trying to solve in the issue you raised.
> 
> Alex

Hi!
My problem here is that i have a lot of my requests, say 95%, that are under 1Mb, but a few are between 1 and 10Mb. Im not pushing really big things otherwise i would have used an external storage or split my payload. Not sure if a 2Mb request is really an issue...

**Comment by CarbonC** [comment]
But more than my use case/the max_payload value, i feel like allowing to pass custom conf to parts of the stack and easily change them with configMaps is a good thing.

**Comment by alexellis** [comment]
We will await your GitHub issue with the full template filled out.

**Comment by albertkohl-monotek** [comment]
i second this! i'm not using helm, but i manually updated my .yml files and deployed it and it worked perfectly.

in my case, i'm using the async functions to pass a json string to send an email. that email can have attachments up to 20mb.

i know it's probably not best-use-case, but it works for me, and makes it so my site can offload the email to python scripts.

**Pull request closed without merging**
