### PR TITLE
Add maxWaiting parameter for jetstream-queue-worker

### PR DESCRIPTION
**Pull request by welteki**
Signed-off-by: Han Verstraete (OpenFaaS Ltd) <han@openfaas.com>

## Description

Add `maxWaiting` parameter for the JetStream queue-worker. Allows users to configure the max waiting pulls for the queue-worker JetStream consumer.

WIP: the JetStream queue-worker needs a new release and the image needs to be updated in this PR.

## Why is this needed?

Allow users to set the MaxWaiting configuration for a consumer without having to create the consumer manually.

## Who is this for?

What company is this for? Are you listed in the [ADOPTERS.md](https://github.com/openfaas/faas/blob/master/ADOPTERS.md) file?

## How Has This Been Tested?

Verified the generated templates and checked the `max_waiting` environment variable is included in the deployment:

```bash
helm template chart/openfaas \
  --set openfaasPro=true \
  --set queueMode=jetstream
```

```bash
helm template chart/queue-worker 
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
@welteki what needs to happen before this can stop being wip?

**Comment by welteki** [comment]
> @welteki what needs to happen before this can stop being wip?

We need to merge the maxWaiting feature for the queue-worker and cut a new release so the image can be updated here.

**Comment by alexellis** [comment]
Image tag 0.3.6 will be ready for testing for you, within a few minutes. Ping me directly when you've been able to confirm the changes from that version and I'll merge this.

**Review by alexellis — APPROVED** [review]
Approved

**Pull request merged**
