### PR TITLE
WIP Update go dependencies

### PR DESCRIPTION
**Pull request by aledbf**
## Description

- Go 1.13.9 is required because of `errors.Is` in API machinery
- Use [clientgofix](https://github.com/kubernetes-sigs/clientgofix) to update client-go calls

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Thank you for taking an interest in updating the client-go to 1.18. What minimum version of Kubernetes is supported after the change?

**Comment by alexellis** [comment]
FYI #631 fixed the issue we saw reported in #630, but there remains an issue with the schema tracked in #634

**Comment by alexellis** [comment]
@aledbf just checking that you saw this question? https://github.com/openfaas/faas-netes/pull/632#issuecomment-625719189

**Comment by aledbf** [comment]
@alexellis from the [compatibility-matrix](https://github.com/kubernetes/client-go/#compatibility-matrix) the oldest version is k8s v1.15 but with the same versions, I know users running v1.12 (from ingress-nginx)

**Comment by alexellis** [comment]
I was chatting to @munnerz about this earlier and he thought it was 1.11, but I have always tended to take the compatibility matrix as the source of truth. I suspect we have users on 1.14 still. cc @LucasRoesler

**Comment by alexellis** [comment]
We are currently on around 1.17 = https://github.com/kubernetes/client-go/tree/v0.17.6

I'm not sure how to reconcile the client-go versions with K8s versions though.

**Comment by munnerz** [comment]
From the compatibility matrix page:

```
- The Kubernetes cluster has features the client-go library can't use, either due to the server has additional new API, or that client-go has removed old API. However, everything they share in common (i.e., most APIs) will work.
```

This part is worth emphasising:

> However, everything they share in common (i.e., most APIs) will work.

The only exception to this would be if API clients began depending upon a core feature of Kubernetes that was introduced in a newer version (as a hypothetical example say, pagination of LIST calls). A change like that however would be clearly documented, and a mitigation usually provided (that may be automatic/transparent as well, e.g. falling back to non-paginated LIST calls).

I would say with a pretty strong level of confidence that it will work fine, especially when considering the wording in the compatibility matrix. Although having your end-to-end suite run against all versions of Kubernetes you support in the project ahead of releasing is still advised 😅

**Comment by aledbf** [comment]
>  Although having your end-to-end suite run against all versions of Kubernetes you support in the project ahead of releasing is still advised

Definitively this is the only way to make sure everything works as expected :smile:

**Comment by alexellis** [comment]
Closing as we have integrated your changes in another commit. Thank you for your support @aledbf

**Pull request closed without merging**
