### PR TITLE
Update faas-provider and populate secrets list in fnc status

### PR DESCRIPTION
**Pull request by LucasRoesler**
## Description

- Update faas-provider to v0.16.1
- When listing or reading the function status, populate the configured
  secrets list. This will happen in both the HTTP handler and the
  operator handlers.

  The `FunctionStatus` instance is now constructed via the
  `k8s.AsFunctionStatus` in the handlers and this should now be
  consistently used anywhere that a `FunctionStaus` was being
  constructed before.

  For the operator, there is now a private utility method
  `toFunctionStatus` that can parse the `Function` CRD type into
  the `FunctionStatus`. This will parse all possible values that
  overlap between the two types and is now used anywhere that a
  `FunctionStatus` was being constructed from the `Function` type.

- Add test to confirm that the parse function can correctly read the
  results from the ConfigureSecrets method.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

From a discussion in slack, this could/will be useful for pipeline workflows and alternative scaling implementations

## How Has This Been Tested?

New unit tests, manual test are WIP

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by LucasRoesler** [comment]
I am a bit confused by the build error, i didn't change anything in that part of the code base

image

comes from this part of the `apply.go`: https://github.com/openfaas/faas-netes/blob/43f64cf9b30fd5f0f56514dee6b9fe01cfbfed45/pkg/server/apply.go#L68-L108

And the very odd thing, you just patched that part of the code to handle the null case!

**Comment by LucasRoesler** [comment]
I have tested the operator directly locally, and deploying echo works

```sh
$ make build-docker
$ git describe --tags
0.12.12-1-g098438c
$ docker tag ghcr.io/openfaas/faas-netes:latest ghcr.io/lucasroesler/faas-netes:0.12.12-1-g098438c
$ docker push ghcr.io/lucasroesler/faas-netes:0.12.12-1-g098438c

$ arkade install openfaas \
    --basic-auth=false --direct-functions=false \
    --operator --clusterrole \
    --set operator.image=ghcr.io/lucasroesler/faas-netes:0.12.12-1-g098438c

$ kubectl port-forward -n openfaas svc/gateway 8080


$ faas-cli deploy --image=functions/alpine:latest --fprocess=cat --name "echo"
$ faas-cli describe echo
$ faas-cli invoke echo <<< "hppy go lucky"
hppy go lucky


$ kubectl describe deploy gateway 
Name:                   gateway
Namespace:              openfaas
CreationTimestamp:      Sun, 20 Dec 2020 19:44:18 +0100
Labels:                 app=openfaas
                        app.kubernetes.io/managed-by=Helm
                        chart=openfaas-6.2.2
                        component=gateway
                        heritage=Helm
                        release=openfaas
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: openfaas
                        meta.helm.sh/release-namespace: openfaas
Selector:               app=gateway
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=gateway
  Annotations:      prometheus.io.port: 8082
                    prometheus.io.scrape: true
  Service Account:  openfaas-operator
  Containers:
   gateway:
    Image:      openfaas/gateway:0.20.2
    Port:       8080/TCP
    Host Port:  0/TCP
    Requests:
      cpu:      50m
      memory:   120Mi
    Liveness:   http-get http://:8080/healthz delay=0s timeout=5s period=10s #success=1 #failure=3
    Readiness:  http-get http://:8080/healthz delay=0s timeout=5s period=10s #success=1 #failure=3
    Environment:
      read_timeout:             65s
      write_timeout:            65s
      upstream_timeout:         60s
      functions_provider_url:   http://127.0.0.1:8081/
      direct_functions:         false
      direct_functions_suffix:  openfaas-fn.svc.cluster.local
      function_namespace:       openfaas-fn
      faas_nats_address:        nats.openfaas.svc.cluster.local
      faas_nats_port:           4222
      faas_nats_channel:        faas-request
      scale_from_zero:          true
      max_idle_conns:           1024
      max_idle_conns_per_host:  1024
    Mounts:                     <none>
   operator:
    Image:      ghcr.io/lucasroesler/faas-netes:0.12.12-1-g098438c
    Port:       8081/TCP
    Host Port:  0/TCP
    Command:
      ./faas-netes
      -operator=true
    Requests:
      cpu:     50m
      memory:  120Mi
    Environment:
      port:                                   8081
      function_namespace:                     openfaas-fn
      profiles_namespace:                     openfaas
      read_timeout:                           60s
      write_timeout:                          60s
      image_pull_policy:                      Always
      http_probe:                             true
      set_nonroot_user:                       false
      readiness_probe_initial_delay_seconds:  2
      readiness_probe_timeout_seconds:        1
      readiness_probe_period_seconds:         2
      liveness_probe_initial_delay_seconds:   2
      liveness_probe_timeout_seconds:         1
      liveness_probe_period_seconds:          2
      cluster_role:                           true
    Mounts:                                   <none>
  Volumes:
   faas-netes-temp-volume:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   gateway-55f44687f4 (1/1 replicas created)
Events:
  Type    Reason             Age    From                   Message
  ----    ------             ----   ----                   -------
  Normal  ScalingReplicaSet  6m38s  deployment-controller  Scaled up replica set gateway-55f44687f4 to 1
```

**Comment by alexellis** [comment]
> I have tested the operator directly locally, and deploying echo works

Can you show the data coming back via curl?

**Comment by alexellis** [comment]
How can I help to get this PR ready for merge?

1) Rebase required due to Dependabot changes being merged
2) No curl output shared, please try, it shouldn't take > 5 mins - https://github.com/openfaas/faas-netes/pull/731#issuecomment-763509843
3) CI is not passing, I don't know why - but most other PRs are passing, so it may need some digging

**Comment by LucasRoesler** [comment]
@alexellis this one passed the checks now, probably because the integration test step is using a newer (fixed) release

**Comment by alexellis** [comment]
Thank you. Can you include a curl output, formatted with jq? Alistair did this for the faasd PR.

**Comment by LucasRoesler** [comment]
@alexellis note that the current gateway image does _not_ forward the secrets

```sh
$ curl http://localhost:8080/system/functions | jq
[
  {
    "name": "echo",
    "image": "functions/alpine:latest",
    "invocationCount": 0,
    "replicas": 1,
    "envProcess": "cat",
    "availableReplicas": 1,
    "labels": {
      "faas_function": "echo",
      "foo": "baz"
    },
    "annotations": {
      "prometheus.io.scrape": "false"
    },
    "namespace": "openfaas-fn"
  }
]
$ curl http://localhost:8081/system/functions | jq
[
  {
    "name": "echo",
    "image": "functions/alpine:latest",
    "namespace": "openfaas-fn",
    "envProcess": "cat",
    "secrets": [
      "creds"
    ],
    "labels": {
      "faas_function": "echo",
      "foo": "baz"
    },
    "annotations": {
      "prometheus.io.scrape": "false"
    },
    "replicas": 1,
    "availableReplicas": 1
  }
]```

**Comment by alexellis** [comment]
I moved the chart to use the latest GHCR image for the gateway which I thought had that change. 

Is this the same result that you had @Waterdrips ?

**Comment by LucasRoesler** [comment]
I installed using 

```sh
arkade install openfaas -a=false --set faasnetes.image=ghcr.io/lucasroesler/faas-netes:731
```

**Comment by LucasRoesler** [comment]
@alexellis  we could consider making the gateway a little dumber for some of these endpoints, which avoid having these kind of schema sync issues

**Comment by alexellis** [comment]
It is a pass through proxy apart from when the gateway needs to enrich the results with Prometheus metrics.

**Comment by alexellis** [comment]
This is the enrichment code - it's also using the latest faas-provider version 0.16.2 - https://github.com/openfaas/faas/blob/master/gateway/metrics/add_metrics.go

**Comment by LucasRoesler** [comment]
@alexellis what do you want to do to finish this PR? the curl shows that the provider is working as expected

**Comment by alexellis** [comment]
There was a comment you made about it not working end to end due to the gateway not bringing the field across, so I commented with the reason (a newer gateway was needed).

So I think we can merge this now.

**Pull request merged**
