### PR TITLE
Bumpe golang to 1.10.x and alpine to 3.8

### PR DESCRIPTION
**Pull request by LucasRoesler**
## Description

- Bump the base docker image to golang:1.10
- Bump the alpine version to 3.8

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

I opened #329 

## How Has This Been Tested?

Manually tested the change using the `docker-for-desktop` Kubernetes

In the faas-netes repo

```sh
make build
kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml
cd chart/openfaas
helm upgrade openfaas --install . \
    --namespace openfaas  \
    --set faasnetesd.image=openfaas/faas-netes:latest \
    --set faasnetesd.imagePullPolicy=IfNotPresent \
    --set basic_auth=false \
    --set openfaasImagePullPolicy=IfNotPresent \
    --set functionNamespace=openfaas-fn
```

Then, in the browser go to http://localhost:31112/ui/ and see the `nodeinfo` function is running and test it

Finally, delete the function in the UI and then check that the related k8s resources were deteled using 

```sh
kubectl -n openfaas-fn get all
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Was just about to merge this then noticed `Bump` written as `Bumpe` in the commit message.

What do you want to do - leave it as is or fix up? @LucasRoesler

**Comment by LucasRoesler** [comment]
I'm ok with it, but I can fix it in about 20mins if you would like

**Comment by LucasRoesler** [comment]
typo fixed

**Comment by alexellis** [comment]
Thanks for the PR

**Pull request merged**
